name: On main push

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
#  releases:
#    uses: ./.github/workflows/releases.yml
#  release-please:
#    uses: ./.github/workflows/release-please.yml

  change-finder:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.check-changes.outputs.projects }}
    steps:
      # Checkout the repository including all tags
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

#      - name: Install dependencies
#        run: npm ci

      - name: Check changes
        id: check-changes
        run: node .github/scripts/check_changes.js

  check-output:
    runs-on: ubuntu-latest
    needs: change-finder
    steps:
      - name: Print outputs
        run: echo ${{ needs.change-finder.outputs.projects }}

  release-please-release:
    runs-on: ubuntu-latest
    needs: change-finder
    strategy:
      fail-fast: false
      matrix:
#        project: ${{needs.changeFinder.outputs.projects}}
        project: ${{fromJSON('["tools/kystrap"]')}}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: tag-release
        with:
          path: ${{ matrix.project }}
          token: ${{ secrets.GITHUB_TOKEN }}
#          release-type: node
          monorepo-tags: true
#          package-name: ${{ matrix.package }}
          command: github-release
#      - uses: actions/checkout@v4
#        if: ${{ steps.tag-release.outputs.releases_created }}
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 8
#      - uses: actions/setup-node@v3
#        if: ${{ steps.tag-release.outputs.releases_created }}
#        with:
#          node-version: 16
#          registry-url: 'https://external-dot-oss-automation.appspot.com/'
#          cache: 'pnpm'
#      - name: publish
#        if: ${{ steps.tag-release.outputs.releases_created }}
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
#        run: |
#          pnpm install
#          pnpm publish --filter ${{ matrix.package }} --no-git-checks --access public