name: On main push

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
#  releases:
#    uses: ./.github/workflows/releases.yml
  release-please:
    uses: ./.github/workflows/release-please.yml
