name: unit tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: "checkout repo"
        uses: actions/checkout@v4
      # Install nodejs
      - name: Install nodejs
        uses: actions/setup-node@v4
      # Install yarn
      - name: Install yarn
        run: npm install --global yarn
      # Run yarn install
      - name: Run yarn install
        run: yarn install
        working-directory: protocol/core
      # Run tests
      - name: "test"
        run: yarn test
        working-directory: protocol/core
